version: "3.1"

services:
  db:
    image: mysql:8.0.4
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: 12345678

volumes:
  dbvolume:

